/*
 * © Merative US L.P. 2021
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.whc.deid.shared.pojo.config.masking;

/**
 * Determines how a privacy provider should react if it encounters input it does not recognize, is
 * in the wrong format, or is otherwise invalid for the provider. Note that not all providers
 * support all of these options, but will substitute another handling method if an unsupported
 * handler is specified.
 */
public enum UnexpectedMaskingInputHandler {

  /**
   * Use null as the masked value.
   */
  NULL,

  /**
   * Use a random value generated by the privacy provider as the masked value.
   */
  RANDOM,

  /**
   * Use the configured value/message as the masked value.
   */
  MESSAGE,

  /**
   * Stop processing and report an error.
   */
  ERROR_EXIT
}
