apiVersion: v2
name: deid
description: A Helm Chart to deploy the Alvearie De-Identification service.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version.  It is normally changed when the chart or application changes.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.2

keywords:
  - ibm
  - health records
  - clinical data
  - alvearie
  - deid

home: https://github.com/Alvearie/de-identification

maintainers:
  - name: Jarrett Anderson
    email: jarrett@us.ibm.com
  - name: Dumas Hwang
    email: dhwang@ca.ibm.com
  - name: Denis Ricard
    email: dricard@ca.ibm.com
