name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up chart-testing (ct)
        uses: helm/chart-testing-action@v2.0.1

      - name: Get changed charts (ct list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs de-identification-app --target-branch master)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Lint charts (ct lint)
        run: ct lint --chart-dirs de-identification-app --target-branch master --validate-maintainers=false --debug

      - name: Create 'kind' cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (ct install)
        run: ct install