name: Build and Publish container Images

on:
  release:
    types: [published, created, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Sanity Test
      run: cd de-identification-app/scripts && ./sanity_test.sh
    - name: back to app directory
      run: cd ..

  buildpushimg:

    runs-on: ubuntu-latest

    steps:
    - name: Get Release Version
      run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Print Release Version
      run: echo $RELEASE_VERSION
    - name: Build Image
      run: docker build -f Dockerfile -t alvearie/de-identification:${{ env.RELEASE_VERSION }} .
    - name: List Docker Images
      run: docker images
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker Images
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker push alvearie/de-identification:${{ env.RELEASE_VERSION }}
