name: Publish Release Image

on:
  workflow_dispatch:
    inputs:
      branchRef:
        decription: 'Release tag to execute on'
        required: true
  release:
    types: [published, edited]

jobs:
  build_push_img:

    runs-on: ubuntu-latest

    steps:
    # Build Java targets
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branchRef }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Sanity Test
      run: cd de-identification-app/scripts && ./sanity_test.sh

    # Build the image and publish
    - name: Get Release Information
      id: release_info
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${{ github.event.inputs.branchRef:GITHUB_REF#refs/tags/ }}
        echo ::set-output name=MVN_RELEASE_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: Print Release Information 
      run: |
        echo $SOURCE_NAME
        echo $SOURCE_BRANCH
        echo $SOURCE_TAG
        echo $MVN_RELEASE_VERSION
      env:
        SOURCE_NAME: ${{ steps.release_info.outputs.SOURCE_NAME }}
        SOURCE_BRANCH: ${{ steps.release_info.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.release_info.outputs.SOURCE_TAG }}
        MVN_RELEASE_VERSION: ${{ steps.release_info.outputs.MVN_RELEASE_VERSION }}
    - name: Build Image
      run: |
        cd de-identification-app
        docker build -f Dockerfile -t alvearie/deid:${{ steps.release_info.outputs.SOURCE_TAG }} .
    - name: List Docker Images
      run: docker images
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker Images
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker push alvearie/deid:${{ steps.release_info.outputs.SOURCE_TAG }}
