# This workflow will build a Java project with Maven and store the jars in Artifactory
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# GitHub Actions: https://docs.github.com/en/actions

name: Java CI with Maven Build and Deploy

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Branch name'
        required: true
      save-jars: 
        description: 'Publish jars to Artifactory'
        required: true
      java8:
        description: 'Perform additional Java 8 build'
        required: true            
  push:
    branches: [ master, release* ]

env:
  ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
  ARTIFACTORY_KEY: ${{ secrets.ARTIFACTORY_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    # do not run on pushes on forks unless explicitly dispatched
    if: ${{ (github.repository == 'Alvearie/de-identification') || (github.event_name == 'workflow_dispatch') }}
    
    steps:
    # Setup some useful vars
    - name: Get Job Info
      id: job_info
      run: |
        set -x
        # get branch name
        # github.event.inputs.tagOrRef is only present if manually launched
        if [ ! -z ${{ github.event.inputs.target-branch }} ]; then
           checkout_branch=${{ github.event.inputs.target-branch }}
        else
           # use event source branch (default)
           checkout_branch=''
        fi        
        echo "CHECKOUT_BRANCH=${checkout_branch}" >> $GITHUB_OUTPUT
        # check for jar publish
        if [ ! -z ${{ github.event.inputs.save-jars }} ]; then
           deploy=${{ github.event.inputs.save-jars }}
        else
           deploy="true"
        fi           
        echo "DEPLOY=${deploy}" >> $GITHUB_OUTPUT
        # check for Java 8 build
        if [ ! -z ${{ github.event.inputs.java8 }} ]; then
           java8=${{ github.event.inputs.java8 }}
        else
           java8="true"
        fi           
        echo "JAVA8=${java8}" >> $GITHUB_OUTPUT
                
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.job_info.outputs.CHECKOUT_BRANCH }}

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
   
    - name: Maven Build and Deploy
      env:
         DEPLOY: ${{ steps.job_info.outputs.DEPLOY }}
      run: chmod u+x build/maven.build-deploy.sh && build/maven.build-deploy.sh

    - name: Sanity Test
      run: cd de-identification-app/scripts && ./sanity_test.sh && cd ../..

    - name: Maven Build and Deploy Java 8
      if: ${{ steps.job_info.outputs.JAVA8 == 'true' }}
      env:
         DEPLOY: ${{ steps.job_info.outputs.DEPLOY }}
         JAVA_COMPILER_RELEASE: 8
      run: chmod u+x build/maven.build-deploy.sh && build/maven.build-deploy.sh
      
    - name: Sanity Test Java 8
      if: ${{ steps.job_info.outputs.JAVA8 == 'true' }}
      env:
         JAVA_COMPILER_RELEASE: 8      
      run: cd de-identification-app/scripts && ./sanity_test.sh && cd ../..
