apiVersion: v1
kind: Service
metadata:
  name: de-identification
  labels:
    app: de-identification
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: deid-port
      protocol: TCP
  selector:
    app: de-identification
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-identification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: de-identification
  template:
    metadata:
      name: de-identification
      labels:
        app: de-identification
    spec:
      containers:
        - name: de-identification
          image: alvearie/deid
          ports:
            - containerPort: 8080